/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kitaponeri;

import com.mysql.jdbc.Connection;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static kitaponeri.adminSayfasi.USER;
import static kitaponeri.uyelikDevamPage.DB_URL;

/**
 *
 * @author dell
 */
public class ekleKitap extends javax.swing.JFrame {

    // JDBC driver name and database URL
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/kitapOneriKullanici";
    
    static final String USER = "root";
    static final String PASS = "1038";
    private static Connection con;
    private static Statement st;
    private static ResultSet rs;

    private static String INSERT_QUERY_KITAP = "INSERT INTO `bx_books` "
            + "(`isbn`, `book_title`, `book_author`, `year_of_publication`, `publisher`, `image_url_s`, `image_url_m`, `image_url_l`) VALUES "
            + "(?,?,?,?,?,?,?,?)";
      
    public ekleKitap() throws SQLException {
        con = con = (Connection) DriverManager.getConnection(DB_URL, USER, PASS);
        st = con.createStatement();
        initComponents();
    }

    private static void kitapEkleDB(String isbn, String book_title, String book_author, String year_of_publication, String publisher, String image_url_s, String image_url_m, String image_url_l) throws SQLException {
        PreparedStatement prpstmt = null;

        prpstmt = con.prepareStatement(INSERT_QUERY_KITAP);
        prpstmt.setString(1, isbn);
        prpstmt.setString(2, book_title);
        prpstmt.setString(3, book_author);
        prpstmt.setString(4, year_of_publication);
        prpstmt.setString(5, publisher);
        prpstmt.setString(6, image_url_s);
        prpstmt.setString(7, image_url_m);
        prpstmt.setString(8, image_url_l);
        // sorguyu gönder
        prpstmt.executeUpdate();

        System.out.println("\n***" + isbn + " : "+book_title+ " kitabi eklendi.");
    }
    
    private boolean kontrolISBN(String isbn) {
        PreparedStatement ps;
        ResultSet rs;
        boolean konrolISBN = false;
        String sqlKontrolISBN = "SELECT * FROM `bx_books` WHERE `isbn` =?";
        
        try {
            ps = con.prepareStatement(sqlKontrolISBN);
            ps.setString(1, isbn);
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                konrolISBN = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(uyelikSayfasi.class.getName()).log(Level.SEVERE, null, ex);
        }
         return konrolISBN;        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isbnText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        kitapAdiText = new javax.swing.JTextField();
        kitapYazariText = new javax.swing.JTextField();
        yayinYiliText = new javax.swing.JTextField();
        yayineviText = new javax.swing.JTextField();
        urlSText = new javax.swing.JTextField();
        urlMText = new javax.swing.JTextField();
        urlLText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        geriButton = new javax.swing.JButton();
        kitapEkleTamamla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        isbnText.setText(" ");
        isbnText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnTextActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Kitap ekelmek icin gerekli bilgileri giriniz.");

        kitapAdiText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapAdiTextActionPerformed(evt);
            }
        });

        kitapYazariText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapYazariTextActionPerformed(evt);
            }
        });

        jLabel2.setText("ISBN:");

        jLabel3.setText("Kitap Adi:");

        jLabel4.setText("Kitap Yazari:");

        jLabel5.setText("Yayın Yılı:");

        jLabel6.setText("Yayınevi:");

        jLabel7.setText("image URL(S):");

        jLabel8.setText("image URL(M):");

        jLabel9.setText("image URL(L):");

        geriButton.setText("<");
        geriButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriButtonActionPerformed(evt);
            }
        });

        kitapEkleTamamla.setText("Tamamla");
        kitapEkleTamamla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kitapEkleTamamlaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kitapEkleTamamla))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(geriButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(urlMText)
                            .addComponent(urlSText)
                            .addComponent(yayineviText)
                            .addComponent(yayinYiliText)
                            .addComponent(isbnText, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(urlLText)
                            .addComponent(kitapAdiText)
                            .addComponent(kitapYazariText))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isbnText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(geriButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(kitapAdiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(kitapYazariText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yayinYiliText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yayineviText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlSText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlMText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(urlLText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(kitapEkleTamamla)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isbnTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnTextActionPerformed

    private void kitapAdiTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapAdiTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitapAdiTextActionPerformed

    private void kitapYazariTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapYazariTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kitapYazariTextActionPerformed

    private void kitapEkleTamamlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kitapEkleTamamlaActionPerformed
        String isbn = isbnText.getText();
        String kitapAdi = kitapAdiText.getText();
        String kitapYazari = kitapYazariText.getText();
        String yayinYili = yayinYiliText.getText();
        String yayinevi = yayineviText.getText();
        String urlS = urlSText.getText();
        String urlM = urlMText.getText();
        String urlL = urlLText.getText();
        
        try {
            if( (isbn.length() != 0) && (kitapAdi.length() != 0) && (kitapYazari.length() != 0) && (yayinYili.length() != 0)
                 && (yayinevi.length() != 0) && (urlS.length() != 0) && (urlM.length() != 0) && (urlL.length() != 0) ){
                 if(kontrolISBN(isbn) == false){
                     kitapEkleDB(isbn, kitapAdi, kitapYazari, yayinYili, yayinevi, urlS, urlM, urlL);
                     adminSayfasi admin = new adminSayfasi();
                     admin.tobloyuDoldur("bx_books");
                 }else{
                     JOptionPane.showMessageDialog(null, "Bu isbn koduna ait kitap daha önce eklenmiş.");
                 }
            }else{
                JOptionPane.showMessageDialog(null, "Lütfen bos alanlari kontrol ediniz.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ekleKitap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_kitapEkleTamamlaActionPerformed

    private void geriButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriButtonActionPerformed
        try {
            adminSayfasi admin = new  adminSayfasi();
            admin.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(ekleKitap.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setVisible(false);
    }//GEN-LAST:event_geriButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ekleKitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ekleKitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ekleKitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ekleKitap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ekleKitap().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ekleKitap.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geriButton;
    private javax.swing.JTextField isbnText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kitapAdiText;
    private javax.swing.JButton kitapEkleTamamla;
    private javax.swing.JTextField kitapYazariText;
    private javax.swing.JTextField urlLText;
    private javax.swing.JTextField urlMText;
    private javax.swing.JTextField urlSText;
    private javax.swing.JTextField yayinYiliText;
    private javax.swing.JTextField yayineviText;
    // End of variables declaration//GEN-END:variables
}
