/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kitaponeri;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static kitaponeri.uyelikDevamPage.DB_URL;

public class loginSayfasi extends javax.swing.JFrame {

    // JDBC driver name and database URL
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/kitapOneriKullanici";
    private static Connection con;

    //  Database credentials
    static final String USER = "root";
    static final String PASS = "1038";

    static String anlikKullaniciIsbn;

    public loginSayfasi() {
        initComponents();
    }

    private boolean giris(String username, String password, String kullanici) {
        try {
            Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
            con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/kitapOneriKullanici?" + "user=root&password=1038");
            PreparedStatement pst = con.prepareStatement("Select * from bx_users where user_name=? and password=? and kullanici=?");
            pst.setString(1, username);
            pst.setString(2, password);
            pst.setString(3, kullanici);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                this.anlikKullaniciIsbn = rs.getString(1);
                return true;
            } else {
                return false;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kullaniciAdi = new javax.swing.JTextField();
        kullaniciAdiLabel = new javax.swing.JLabel();
        sifreLabel = new javax.swing.JLabel();
        uyelikYokMu = new javax.swing.JButton();
        Giris = new javax.swing.JButton();
        kullaniciSifre = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        adminGiris = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kullaniciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullaniciAdiActionPerformed(evt);
            }
        });

        kullaniciAdiLabel.setText("Kullanici Adi:");

        sifreLabel.setText("Şifre:");

        uyelikYokMu.setText("Üyeliginiz yok mu?");
        uyelikYokMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyelikYokMuActionPerformed(evt);
            }
        });

        Giris.setText("GIRIS");
        Giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirisActionPerformed(evt);
            }
        });

        jLabel1.setText("KİTAP ÖNERİ");

        adminGiris.setText("ADMIN GIRISI");
        adminGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminGirisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sifreLabel)
                                    .addComponent(kullaniciAdiLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kullaniciSifre, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                        .addComponent(kullaniciAdi))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Giris)
                                .addGap(18, 18, 18))
                            .addComponent(adminGiris)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(uyelikYokMu)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kullaniciAdiLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifreLabel)
                    .addComponent(kullaniciSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(Giris)
                .addGap(18, 18, 18)
                .addComponent(adminGiris)
                .addGap(18, 18, 18)
                .addComponent(uyelikYokMu)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kullaniciAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullaniciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kullaniciAdiActionPerformed

    private void uyelikYokMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyelikYokMuActionPerformed
        // TODO add your handling code here:
        uyelikSayfasi uyelik = new uyelikSayfasi();
        uyelik.setSize(500, 500);
        uyelik.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_uyelikYokMuActionPerformed

    private void GirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirisActionPerformed
        if (kullaniciAdi.getText().length() == 0) // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, "Kullanici adi bos birakilamaz.Lütfen konrol edip güncelleyiniz!");
        } else if (kullaniciSifre.getPassword().length == 0) // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, "Bos alanlari lütfen konrol edip güncelleyiniz!");
        } else {
            String userName = kullaniciAdi.getText();   // Collecting the input
            char[] pass = kullaniciSifre.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass);  // converting from array to string
            if (giris(userName, pwd, "user")) {
                //JOptionPane.showMessageDialog(null, "Correct Login Credentials");
                anaSayfa anasayfa;
                try {
                    anasayfa = new anaSayfa();
                    anasayfa.setSize(900, 600);
                    anasayfa.setVisible(true);
                    this.setVisible(false);
                } catch (IOException ex) {
                    Logger.getLogger(loginSayfasi.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Incorrect Login Credentials");
            }
        }
    }//GEN-LAST:event_GirisActionPerformed

    private void adminGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminGirisActionPerformed
        if (kullaniciAdi.getText().length() == 0) // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, "Kullanici adi bos birakilamaz.Lütfen konrol edip güncelleyiniz!");
        } else if (kullaniciSifre.getPassword().length == 0) // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, "Bos alanlari lütfen konrol edip güncelleyiniz!");
        } else {
            String userName = kullaniciAdi.getText();   // Collecting the input
            char[] pass = kullaniciSifre.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass);  // converting from array to string
            if (giris(userName, pwd, "admin")) {
                //JOptionPane.showMessageDialog(null, "Correct Login Credentials");
                adminSayfasi admin;
                try {
                    admin = new adminSayfasi();
                    admin.setSize(990, 600);
                    admin.setVisible(true);
                    this.setVisible(false);
                } catch (SQLException ex) {
                    Logger.getLogger(loginSayfasi.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Incorrect Login Credentials");
            }
        }
    }//GEN-LAST:event_adminGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginSayfasi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginSayfasi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginSayfasi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginSayfasi.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new loginSayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Giris;
    private javax.swing.JButton adminGiris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField kullaniciAdi;
    private javax.swing.JLabel kullaniciAdiLabel;
    private javax.swing.JPasswordField kullaniciSifre;
    private javax.swing.JLabel sifreLabel;
    private javax.swing.JButton uyelikYokMu;
    // End of variables declaration//GEN-END:variables
}
