/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kitaponeri;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static kitaponeri.KitapOneri.DB_URL;
import static kitaponeri.loginSayfasi.DB_URL;

/**
 *
 * @author dell
 */
public class uyelikSayfasi extends javax.swing.JFrame {

    // JDBC driver name and database URL
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost/kitapOneriKullanici";

    //  Database credentials
    static final String USER = "root";
    static final String PASS = "1038";
    private static Connection con;

    private static String INSERT_QUERY_UYELIK = "INSERT INTO `bx_users` "
            + "(`location`, `age`, `user_name`, password) VALUES "
            + "(?,?,?,?)";

    public uyelikSayfasi() {
        initComponents();
        con = null;
        Statement stmt = null;
        try {
            //STEP 2: Register JDBC driver
            Class.forName("com.mysql.jdbc.Driver");

            //STEP 3: Open a connection
            System.out.println("(uyelikSayfasi)Connecting to database...");
            con = (Connection) DriverManager.getConnection(DB_URL, USER, PASS);

            //int i = 0;
            /*while (satir != null) {    //veri tabanına BX-USERS dosyasındaki verilerin eklenmesi
             //System.out.println("i---->" +i);
             satir = reader.readLine();
             String[] temp = satir.split(";");

             int boyut = temp.length;
             for (int j = 0; j < boyut; j++) {
             //System.out.println("--->  " + j + temp[j]);
             }
             //i++;
             //if(i > 275394){
             uyeEkle(Integer.valueOf(temp[0]), temp[1], temp[2]);
             //}
             }*/
        } catch (SQLException se) {
            //Handle errors for JDBC
            se.printStackTrace();
        } catch (Exception e) {
            //Handle errors for Class.forName
            e.printStackTrace();
        }
    }

    private static void uyeEkle(String location, String age, String user_name, String password) throws SQLException {
        PreparedStatement prpstmt = null;

        prpstmt = con.prepareStatement(INSERT_QUERY_UYELIK);
        prpstmt.setString(1, location);
        prpstmt.setString(2, age);
        prpstmt.setString(3, user_name);
        prpstmt.setString(4, password);

        // sorguyu gönder
        prpstmt.executeUpdate();

        System.out.println("\n***" + user_name + "  kullanıcısı eklendi.");
    }

    private boolean kontrolUserName(String user_name) {
        PreparedStatement ps;
        ResultSet rs;
        boolean konrolUserName = false;
        String sqlKontrolKullaniciAdi = "SELECT * FROM `bx_users` WHERE `user_name` =?";
        
        try {
            ps = con.prepareStatement(sqlKontrolKullaniciAdi);
            ps.setString(1, user_name);
            rs = ps.executeQuery();
            
            if(rs.next())
            {
                konrolUserName = true;
            }
        } catch (SQLException ex) {
            System.out.println("kontrolUserName catch e düstü.");
            Logger.getLogger(uyelikSayfasi.class.getName()).log(Level.SEVERE, null, ex);
        }
         return konrolUserName;        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        konumLabel = new javax.swing.JLabel();
        yasLabel = new javax.swing.JLabel();
        konumText = new javax.swing.JTextField();
        yasText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        uyelikDevam = new javax.swing.JButton();
        sifreBelirle = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        uyelikUserName = new javax.swing.JTextField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        konumLabel.setText("Konumuzu giriniz: ");

        yasLabel.setText("Yasinizi giriniz:");

        konumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konumTextActionPerformed(evt);
            }
        });

        jLabel1.setText("UYELIK ICIN BILGILERIZI GIRINIZ");

        uyelikDevam.setText("Devam");
        uyelikDevam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uyelikDevamActionPerformed(evt);
            }
        });

        sifreBelirle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreBelirleActionPerformed(evt);
            }
        });

        jLabel2.setText("Sifre belirleyiniz:");

        jLabel4.setText("User name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(uyelikDevam)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(yasLabel)
                            .addComponent(konumLabel)
                            .addComponent(jLabel2))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(konumText, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(yasText)
                            .addComponent(sifreBelirle)
                            .addComponent(uyelikUserName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)))
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(uyelikUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(konumLabel)
                    .addComponent(konumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yasLabel)
                    .addComponent(yasText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sifreBelirle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(uyelikDevam)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void konumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_konumTextActionPerformed

    private void uyelikDevamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uyelikDevamActionPerformed
        // TODO add your handling code here:
        String userName = uyelikUserName.getText();
        String location = konumText.getText();
        String age = yasText.getText();
        String password = String.valueOf(sifreBelirle.getPassword());
        
        if (userName.length() == 0) // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, "Kullanici adi bos birakilamaz.Lütfen konrol edip güncelleyiniz!");
        } else if (password.length() == 0) // Checking for empty field
        {
            JOptionPane.showMessageDialog(null, "Sifre bos birakilamaz.Lütfen konrol edip güncelleyiniz!");
        } else if(kontrolUserName(userName))
        {
            JOptionPane.showMessageDialog(null, "Bu kallanici adi kullanimda!");
        }
        
        try {
            if( (userName.length() != 0) && (password.length() != 0) && (kontrolUserName(userName) == false) ){
                uyeEkle(location, age, userName, password);
                uyelikDevamPage uyelikD = new uyelikDevamPage();
                uyelikD.setSize(700, 1000);
                uyelikD.setVisible(true);
                this.setVisible(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(uyelikSayfasi.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(uyelikSayfasi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_uyelikDevamActionPerformed

    private void sifreBelirleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreBelirleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sifreBelirleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uyelikSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uyelikSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uyelikSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uyelikSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uyelikSayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel konumLabel;
    private javax.swing.JTextField konumText;
    private javax.swing.JPasswordField sifreBelirle;
    private javax.swing.JButton uyelikDevam;
    private javax.swing.JTextField uyelikUserName;
    private javax.swing.JLabel yasLabel;
    private javax.swing.JTextField yasText;
    // End of variables declaration//GEN-END:variables
}
